// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DebugAppendEntry() {
  return window['go']['main']['App']['DebugAppendEntry']();
}

export function DebugRaidTest(arg1) {
  return window['go']['main']['App']['DebugRaidTest'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OnKeepAliveCallback() {
  return window['go']['main']['App']['OnKeepAliveCallback']();
}

export function OnRaidCallback(arg1) {
  return window['go']['main']['App']['OnRaidCallback'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}
