// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function DebugAppendEntry():Promise<void>;

export function DebugRaidTest(arg1:string):Promise<void>;

export function GetServerPort():Promise<number>;

export function OnKeepAliveCallback():Promise<void>;

export function OnRaidCallback(arg1:backend.RaidCallbackParam):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function StartClip(arg1:string,arg2:number):Promise<void>;

export function StopClip():Promise<void>;
