// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function DebugAppendEntry():Promise<void>;

export function DebugRaidTest(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function OnKeepAliveCallback():Promise<void>;

export function OnRaidCallback(arg1:backend.RaidCallbackParam):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;
