// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DebugAppendEntry() {
  return window['go']['main']['App']['DebugAppendEntry']();
}

export function DebugRaidTest(arg1) {
  return window['go']['main']['App']['DebugRaidTest'](arg1);
}

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function OnConnectedCallback() {
  return window['go']['main']['App']['OnConnectedCallback']();
}

export function OnKeepAliveCallback() {
  return window['go']['main']['App']['OnKeepAliveCallback']();
}

export function OnRaidCallback(arg1) {
  return window['go']['main']['App']['OnRaidCallback'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function StartClip(arg1, arg2) {
  return window['go']['main']['App']['StartClip'](arg1, arg2);
}

export function StopClip() {
  return window['go']['main']['App']['StopClip']();
}
