// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DebugAppendEntry() {
  return window['go']['main']['App']['DebugAppendEntry']();
}

export function DebugRaidTest(arg1) {
  return window['go']['main']['App']['DebugRaidTest'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OnConnectedCallback() {
  return window['go']['main']['App']['OnConnectedCallback']();
}

export function OnKeepAliveCallback() {
  return window['go']['main']['App']['OnKeepAliveCallback']();
}

export function OnRaidCallback(arg1) {
  return window['go']['main']['App']['OnRaidCallback'](arg1);
}

export function OpenDiectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDiectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartClip(arg1, arg2) {
  return window['go']['main']['App']['StartClip'](arg1, arg2);
}

export function StopClip() {
  return window['go']['main']['App']['StopClip']();
}

export function StopObsStream() {
  return window['go']['main']['App']['StopObsStream']();
}
